env:
  browser: true
extends: 'standard'
globals:
  kintone: true
parser: 'babel-eslint'
rules:
  # 戻り値を受け取らないnew() は認める
  no-new: off
  # console.log を残さない console.warn/error はOK
  no-console:
    - error
    - allow:
      - warn
      - error
  # 原則letよりconstを使う
  prefer-const: error

  # prettierと被る設定はOFF
  arrow-spacing: off
  block-spacing: off
  brace-style: off
  comma-dangle: off
  comma-spacing: off
  comma-style: off
  dot-location: off
  eol-last: off
  func-call-spacing: off
  generator-star-spacing: off
  indent: off
  key-spacing: off
  keyword-spacing: off
  new-parens: off
  no-extra-parens: off
  no-floating-decimal: off
  no-mixed-spaces-and-tabs: off
  no-multi-spaces: off
  no-multiple-empty-lines: off
  no-trailing-spaces: off
  no-whitespace-before-property: off
  object-property-newline: off
  operator-linebreak: off
  padded-blocks: off
  rest-spread-spacing: off
  semi: off
  semi-spacing: off
  space-before-blocks: off
  space-before-function-paren: off
  space-in-parens: off
  space-infix-ops: off
  space-unary-ops: off
  standard/array-bracket-even-spacing: off
  standard/computed-property-even-spacing: off
  standard/object-curly-even-spacing: off
  template-curly-spacing: off
  template-tag-spacing: off
  unicode-bom: off
  wrap-iife: off
  yield-star-spacing: off
  curly: off
  quotes: off
  no-mixed-operators: off
  no-tabs: off
  no-unexpected-multiline: off