env:
  browser: true
extends: 'standard'
globals:
  kintone: true
parser: 'babel-eslint'
rules:
  # 戻り値を受け取らないnew() は認める
  no-new: off
  # 関数名と()の間はスペースを空けない
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
